version: "3"

services:
  site:
    build:
      context: .
      args:
        BASE_URL: "https://${SITE_DOMAIN}/"
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SITE_NAME}.middlewares=global-compress@docker,global-sec@docker,global-cache@docker"

networks:
  dokploy-network:
    external: true